const CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const CONFLICT = 409;
const UNPROCESSABLE_ENTITY = 422;

module.exports = {
	CREATED,
	BAD_REQUEST,
	NOT_FOUND,
	CONFLICT,
	UNPROCESSABLE_ENTITY,
};
