@PORT=3001

@HOST=http://localhost

@URL={{HOST}}:{{PORT}} 

# Recipe

### Read request all dishes
GET {{URL}}/recipes HTTP/1.1

### Read name filter by query
GET {{URL}}/recipes?name=Cauliflower HTTP/1.1

### Read filter petition for id
GET {{URL}}/recipes/716426 HTTP/1.1

### Create new recipe
POST {{URL}}/recipes HTTP/1.1
Content-Type: application/json

{
  "name": "my dish",
  "summary": "a bit of everything",
	"healthScore": 3,
	"step": ["first have a kitchen", "know how to cook"],
	"diets": ["gluten free", "dairy free", "paleolithic"]
}

# Diet

### Read request all diets
GET {{URL}}/diet/ HTTP/1.1